name: Python Package
on:
  push:
    branches:
      - main
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2

      - name: Set Up Python 3.X
        uses: actions/setup-python@v2
        with:
          python-version: 3.X
      - name: Display Python Version
        run: python -c "import sys; print(sys.version)"
