name: Python Package
on:
  push:
    branches:
      - main
jobs:
  build: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        max-parallel: 4
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
    steps: 
      - uses: actions/checkout@v2

      - name: Set Up Python $
        uses: actions/setup-python@v2
        with:
          python-version: $
      - name: Display Python Version
        run: python -c "import sys; print(sys.version)"
