name: Python Package
on:
  push:
    branches:
      - main
jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2

      - name: Set Up Python 3.5
        uses: actions/setup-python@v2
        with:
          python-version: 3.5
      - name: Display Python Version
        run: python -c "import sys; print(sys.version)"
