name: Python Package
on:
  push:
    branches:
      - main
# part
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dev dependencies
        run: pip install -r requirements-dev.txt
      - name: Test with pytest
        run: | 
          pytest -q test.py 
